<?php

require_once dirname(__FILE__) . '/../../lib/binaraHTTPHelper.php';

/**
 * Test class for binaraHTTPHelper.
 * Generated by PHPUnit on 2012-07-21 at 13:57:00.
 */
class binaraHTTPHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var binaraHTTPHelper
     */
    protected $httpHelper;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->httpHelper = binaraHTTPHelper::instance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        @session_destroy();
    }

    /**
     * @covers binaraHTTPHelper::instance
     * @covers binaraHTTPHelper::__construct
     */
    public function testInstance() {
        $this->assertTrue(binaraHTTPHelper::instance() instanceof binaraHTTPHelper);
    }

    /**
     * @covers binaraHTTPHelper::sendHeaders
     */
    public function testSendHeaders() {
        $this->assertTrue($this->httpHelper->sendHeaders(array('Test-header' => 'test-value')));
    }

    public function testSetSessionValue() {
        $this->httpHelper->setSessionValue('test-key', 'test-value');
        $this->assertEquals('test-value', $_SESSION['test-key']);
    }

    public function testGetSessionValue() {
        $_SESSION['example-key'] = 'example-value';
        $this->assertEquals('example-value', $this->httpHelper->getSessionValue('example-key'));
    }

}

?>
