<?php

require_once dirname(__FILE__) . '/../../lib/binaraMathHelper.php';

/**
 * Test class for binaraMathHelper.
 * Generated by PHPUnit on 2012-07-21 at 20:16:53.
 */
class binaraMathHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var binaraMathHelper
     */
    protected $numericUtility;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->numericUtility = binaraMathHelper::instance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers binaraMathHelper::instance
     * @covers binaraMathHelper::__construct
     */
    public function testInstance() {
        $this->assertTrue(binaraMathHelper::instance() instanceof binaraMathHelper);
    }

    /**
     * @covers binaraMathHelper::generateRandomNumber
     */
    public function testGenerateRandomNumber() {
        $result = $this->numericUtility->generateRandomNumber(10, 15);
        $this->assertGreaterThan(9, $result);
        $this->assertLessThan(16, $result);
    }

}

?>
